// app/components/ExternalLink.tsx
import { ArrowUpRight } from "react-feather";

interface ExternalLinkProps {
  href: string;
  children?: React.ReactNode;
}

export const ExternalLink: React.FC<ExternalLinkProps> = (props) => {
  const { href, children } = props;
  return (
    <a
      href={href}
      target="_blank"
      className={`
        text-[color:rgb(var(--secondary-rgb))]
        mt-4
        inline-flex
        underline
        decoration-transparent 
        items-start
        duration-200
        hover:decoration-[color:rgb(var(--secondary-rgb))]
`}
    >
      {children}
      <ArrowUpRight size="1.5rem" strokeWidth={0.8} />
    </a>
  );
};

// src/components/ExternalLink.svelte
<script lang="ts">
  import PhArrowUpRightThin from "~icons/ph/arrow-up-right-thin";

  export let href: string;
  export let label: string;
</script>

<a
  {href}
  target="_blank"
  class={`
        text-blue
        mt-4
        inline-flex
        underline
        decoration-transparent 
        items-start
        duration-200
        hover:decoration-[color:rgb(var(--secondary-rgb))]
`}
>
  {label}
  <PhArrowUpRightThin class="w-6 h-6" />
</a>
